# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-existing-docker-compose/.devcontainer/docker-compose.yml
# https://code.visualstudio.com/docs/remote/create-dev-container


services:
 nginx:
  container_name: nginx
  build:
    context: ./nginx
    dockerfile: .devcontainer/Dockerfile
  depends_on:
    - backend
    - frontend
  ports:
   - 80:80
   - 443:443
  volumes:
    # Mount the root folder that contains .git
    - .:/workspace:cached
  command: nginx -g 'daemon off;'

 postgres:
  container_name: postgres
  build: 
    context: ./database/postgres
    dockerfile: .devcontainer/Dockerfile
  volumes:
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"

 backend:
  container_name: backend
  depends_on:
   - postgres
  build:
    context: ./backend
    dockerfile: .devcontainer/Dockerfile
  volumes:
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"

 frontend:
  container_name: frontend
  depends_on:
   - backend
  build:
    context: ./frontend
    dockerfile: .devcontainer/Dockerfile
  volumes:
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"


