# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-existing-docker-compose/.devcontainer/docker-compose.yml

# what is ..:/app:cached
# from https://code.visualstudio.com/docs/remote/create-dev-container
# Mounts the project folder to '/workspace'. The target path inside the container
# should match what your application expects. In this case, the compose file is
# in a sub-folder, so you will mount '..'. You would then reference this path as the
# 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.

# tldr: if you make changes to your code in container, these changes will be applied
# to code in host

services:
 nginx:
  container_name: nginx
  build:
    context: ./nginx
    dockerfile: .devcontainer/Dockerfile
  depends_on:
    - backend
    - frontend
  ports:
   - 80:80
   - 443:443
  volumes:
    # Mount the root folder that contains .git
    - .:/workspace:cached
  command: nginx -g 'daemon off;'

 postgres:
  container_name: postgres
  build: 
    context: ./database/postgres
    dockerfile: .devcontainer/Dockerfile
  volumes:
    # Mount the root folder that contains .git
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"

 backend:
  container_name: backend
  depends_on:
   - postgres
  build:
    context: ./servus
    dockerfile: .devcontainer/Dockerfile
  links:
    - "postgres:db"
  volumes:
    # Mount the root folder that contains .git
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"

 frontend:
  container_name: frontend
  depends_on:
   - backend
  build:
    context: ./frontend
    dockerfile: .devcontainer/Dockerfile
  volumes:
    # Mount the root folder that contains .git
    - .:/workspace:cached
  command: /bin/sh -c "while sleep 1000; do :; done"


