services:
 postgres:
  container_name: postgres
  build: ./postgres
  volumes:
   - ./postgres/data:/var/lib/postgresql/data
  ports:
   - 5432:5432

 pgadmin:
  container_name: pgadmin
  depends_on:
   - postgres
  image: dpage/pgadmin4
  environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=root
  ports:
   - 5050:80

 backend:
  container_name: backend
  depends_on:
   - postgres
  build: ./servus
  volumes:
   - ./uploads:/app/uploads
   - ./devCerts/mkcert_root.pem:/usr/local/share/ca-certificates/mkcert_root.pem
   - ./devCerts:/app/certs
  ports:
   - 3333:3333

 elven:
  container_name: elven
  depends_on:
   - backend
  build: ./elven
  volumes:
   - ./builded/elven:/app/elven
  ports:
   - 3000:3000

 nginx:
  container_name: nginx
  depends_on:
   - backend
  build: ./nginx
  volumes:
   - ./uploads:/app/uploads
   - ./nginx/logs:/var/log/nginx
   - ./devCerts/mkcert_root.pem:/usr/local/share/ca-certificates/mkcert_root.pem
   - ./devCerts:/app/certs
   - ./builded/elven:/app/elven
  ports:
   - 443:443

